/*
 * HEATING_ELEMENT_INTERFACE.h
 *
 * 
 *  Author: Hager, shorouk, Omar, Mohamed
 */ 


#ifndef HEATING_ELEMENT_INTERFACE_H_
#define HEATING_ELEMENT_INTERFACE_H_

void HEATING_ELEMENT_INIT(void);
void HEATING_ELEMENT_START(void);
void HEATING_ELEMENT_STOP(void);
void HEATING_ELEMENT_TOGGLE(void);

#endif /* HEATING_ELEMENT_INTERFACE_H_ */